name: Test

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - run: mkdir -p artifact-1 && echo test1 > artifact-1/test1.txt
      - run: mkdir -p artifact-2 && echo test2 > artifact-2/test2.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-1
          path: artifact-1
          
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-2
          path: artifact-2        

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Zip Again
        run: |
          mkdir assets
          cd artifacts
          for i in */; do (cd "$i"; zip -r "../../assets/${i%/}.zip" .); done
          cd -
          
      - run: |
          echo 'ARTIFACTS<<EOF' >> $GITHUB_ENV
          find assets -type f -follow -print >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.run_number }}"
          message: "Latest release"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.run_number }}"
          files: ${{ env.ARTIFACTS }}
